version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.6
    environment:
      YTDL_TEST_SET: core
      YTDL_TEST_SET: download
    steps:
      - checkout
      - run: ./devscripts/run_tests.sh
